name: Build clash-tray
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >-
            zip
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-clang-tools-extra
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-qt6-base

      - name: build
        run: |
          mkdir build
          cmake -B build -G Ninja
          cmake --build build

      - name: deploy
        run: |
          mkdir release
          cp build/*.exe release/
          cd release
          windeployqt-qt6.exe --no-compiler-runtime --no-translations --no-libraries  --no-system-d3d-compiler --skip-plugin-types generic,networkinformation,tls --exclude-plugins qgif,qjpeg *.exe
          ldd *.exe |grep clang64  | awk -F\> '{print $2}' | awk -F ' ' '{print $1}' | xargs -I {} cp {} ./
          zip -r clashtray.zip .

      - name: upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clash-tray
          path: |
            release/*.zip

  Upload-Release:
    permissions: write-all
    if: ${{ github.ref_type=='tag' }}
    needs: [build]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: ${{  success() }}
        with:
          tag_name: ${{ github.ref_name }}
          files: bin/*
          generate_release_notes: true
